import './globals.css';
import { faRightFromBracket, faUser } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import Image from 'next/image';
import Link from 'next/link';

export const metadata = {
  title: 'Create School App',
  description: 'Generated by create school app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // #DFE0DF''
  return (
    <html lang="en">
      <body
        style={{ backgroundColor: '#dbb3b3' }}
        className="overflow-x-hidden overflow-y-auto h-screen"
      >
        <div className=" flex justify-between  items-center p-0 py-0 text-black">
          <Link href="/">
            <Image
              src="/image/Sky.jpg"
              width="150"
              height="50"
              alt="logo"
              className="text-2xl text-black  transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-110 cursor-pointer w-16 md:w-24 lg:w-32"
            />
          </Link>

          <ul className="flex space-x-5  md:flex ">
            <li className="p-1  ">
              <Link href="/landingpage">
                <FontAwesomeIcon
                  icon={faUser}
                  height="40"
                  width="40"
                  className=" text-2xl ml-0 text-black hover:text-green-500 transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-110 cursor-pointer md:h-8 md:w-8 "
                />
                Login
              </Link>
            </li>
            <li className="p-1  ">
              <Link href="/logout">
                <FontAwesomeIcon
                  icon={faRightFromBracket}
                  height="40"
                  width="40"
                  className="text-2xl text-black hover:text-green-500 transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-110 cursor-pointer md:h-8 md:w-8"
                />
                logout
              </Link>
            </li>
          </ul>
        </div>

        {children}
      </body>
    </html>
  );
}
