// import './globals.css';

import Link from 'next/link';

export const metadata = {
  title: 'Create School App',
  description: 'Generated by create school app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Link href="/register">register</Link>
        <Link href="/login">login</Link>
        {children}
      </body>
    </html>
  );
}
